import "./globals.css";
import "@radix-ui/themes/styles.css";

import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import localFont from "next/font/local";

import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../../public/PretendardVariable.woff2",
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

import { Providers } from "@/components/Providers";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <Providers>
          <Theme>
            <Navbar />
              {children}
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
