services:
  # Redis service
  redis:
    image: redis:7-alpine
    container_name: sirubot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sirubot-network
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Lavalink service
  lavalink:
    image: fredboat/lavalink:4
    container_name: sirubot-lavalink
    ports:
      - "2111:2111"
    networks:
      - sirubot-network
    volumes:
      - ../lavalink/application.yml:/opt/Lavalink/application.yml
      - ../lavalink/plugins:/opt/Lavalink/plugins
    restart: always

  # Bot service
  bot:
    build:
      context: ..
      dockerfile: Dockerfile
      target: bot
    container_name: sirubot-bot
    env_file:
      - ../apps/bot/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - LAVALINK_HOSTS=NODE-1_sirubot-lavalink_2111_youshallnotpass
      - NODE_ENV=production
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sirubot-network

  # Dashboard service
  dashboard:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dashboard
    container_name: sirubot-dashboard
    ports:
      - "3100:3000"
    env_file:
      - ../apps/dashboard/.env
    environment:
      - DATABASE_URL=postgresql://postgres.ondbwswypzwxzwsywoda:litsybot2256@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - sirubot-network
      - dokploy-network

networks:
  sirubot-network:
    driver: bridge
  dokploy-network:
    external: true

volumes:
  redis-data:
