-- AlterTable
ALTER TABLE "Guild" ADD COLUMN "gaplessEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Guild" ADD COLUMN "crossfadeEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Guild" ADD COLUMN "crossfadeMs" INTEGER NOT NULL DEFAULT 5000;
